# This is a basic workflow to help you get started with Actions

name: CI2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@cp_instead_of_deleting
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'master'
          destination-github-username: 'navafe01'
          destination-repository-name: 'fidotestprod'
